[package]
name = "csv_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1"
encoding_rs = "0.8"
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
anyhow = "1"
encoding_rs_io = "0.1"
